"""
DBSchema module defining database table and field names as enums and constants.
This module provides a centralized schema definition for the database used in this package."""

from enum import Enum

class DBTableNames(str, Enum):
    OWNERS = "owners"
    REPOS = "downstream_repos"
    DOWNSTREAM_REPO_INFO = "downstream_repo_info"
    FILES = "reused_files"
    SIGNATURES = "signatures"
    SIG_TO_FILE = "signatures_to_reused_files"
    REUSED_TEXT_MATCHES = "reused_files_text_matches"
    MODELS = "models"
    FILE_TO_MODEL = "reused_files_to_models"
    FILE_SIGNATURE_MATCHES = "reused_files_signature_matches"
    COMMITS = "commits"
    COMMIT_COMMENTS = "commit_comments"
    COMMIT_PREVIOUS_FILENAMES = "commit_previous_filenames"
    ISSUES = "issues"
    ISSUE_COMMENTS = "issue_comments"
    PULL_REQUESTS = "pull_requests"
    PULL_REQUESTS_TO_COMMITS = "pull_requests_to_commits"
    DISCUSSIONS = "discussions"
    RELEASES = "releases"
    TAGS = "tags"
    REUSED_FILES_TO_RELEASES = "reused_files_to_releases"
    FILE_MODEL_SNAPSHOTS_LISTS_RELEASES = "reused_files_model_snapshots_lists_for_releases"
    BRANCHES = "branches"
    RELEASE_BRANCH_REACHABILITY = "release_branch_reachability"
    RELEASE_LINE_ASSIGNMENTS = "release_line_assignments"
    RELEASE_LINES = "release_lines"
    RELEASE_LINE_MODEL_CHANGES = "release_line_model_changes"


class DBFieldNames:
    class Owners:
        ID = "id"
        OWNER_ID = "owner_id"
        NAME = "name"
        API_URL = "api_url"
        HTML_URL = "html_url"
        TYPE = "type"

    class Repos:
        ID = "id"
        REPO_ID = "repo_id"
        NAME = "name"
        FULL_NAME = "full_name"
        FORK = "fork"
        API_URL = "api_url"
        HTML_URL = "html_url"
        OWNER_ID = "owner_id"

    class DownstreamRepoInfo:
        ID = "id"
        FULL_NAME = "full_name"
        PRIVATE = "private"
        DESCRIPTION = "description"
        FORK = "fork"
        CREATED_AT = "created_at"
        UPDATED_AT = "updated_at"
        PUSHED_AT = "pushed_at"
        GIT_URL = "git_url"
        HOMEPAGE = "homepage"
        SIZE = "size"
        STARGAZERS_COUNT = "stargazers_count"
        WATCHERS_COUNT = "watchers_count"
        LANGUAGE = "language"
        HAS_ISSUES = "has_issues"
        HAS_PROJECTS = "has_projects"
        HAS_DOWNLOADS = "has_downloads"
        HAS_WIKI = "has_wiki"
        HAS_PAGES = "has_pages"
        HAS_DISCUSSIONS = "has_discussions"
        FORKS_COUNT = "forks_count"
        ARCHIVED = "archived"
        DISABLED = "disabled"
        OPEN_ISSUE_COUNT = "open_issue_count"
        LICENSE_KEY = "license_key"
        LICENSE_NAME = "license_name"
        LICENSE_SPDX_ID = "license_spdx_id"
        LICENSE_URL = "license_url"
        LICENSE_NODE_ID = "license_node_id"
        ALLOW_FORKING = "allow_forking"
        IS_TEMPLATE = "is_template"
        TOPICS = "topics"
        VISIBILITY = "visibility"
        FORKS = "forks"
        OPEN_ISSUES = "open_issues"
        PULLS = "pulls"
        WATCHERS = "watchers"
        COMMITS = "commits"
        DEFAULT_BRANCH = "default_branch"
        NETWORK_COUNT = "network_count"
        SUBSCRIBERS_COUNT = "subscribers_count"
        INFO_COLLECTION_STATUS = "info_collection_status"
        PRELIMINARY_FILTER_STATUS = "preliminary_filter_status"
        STATIC_ANALYSIS_STATUS = "static_analysis_status"
        COMMIT_COLLECTION_STATUS = "commit_collection_status"
        ISSUE_COLLECTION_STATUS = "issue_collection_status"
        PULL_COLLECTION_STATUS = "pull_collection_status"
        DISCUSSION_COLLECTION_STATUS = "discussion_collection_status"
        COMMIT_COMMENT_COLLECTION_STATUS = "commit_comment_collection_status"
        RELEASE_COLLECTION_STATUS = "release_collection_status"
        TAG_COLLECTION_STATUS = "tag_collection_status"
        RELEASE_FILTER_STATUS = "release_filter_status"
        BRANCH_COLLECTION_STATUS = "branch_collection_status"

    class Files:
        ID = "id"
        NAME = "name"
        PATH = "path"
        SHA = "sha"
        API_URL = "api_url"
        HTML_URL = "html_url"
        REPO_ID = "repo_id"
        CONTENT_COLLECTION_STATUS = "content_collection_status"

    class Signatures:
        ID = "id"
        IMPORT = "import"
        CALL = "call"
        PREFIX_1 = "prefix_1"
        PREFIX_2 = "prefix_2"
        COLLECTION_STATUS_1 = "collection_status_1"
        COLLECTION_STATUS_2 = "collection_status_2"
        COLLECTION_TIME_1 = "collection_time_1"
        COLLECTION_TIME_2 = "collection_time_2"

    class SigToFile:
        ID = "id"
        SIGNATURE_ID = "signature_id"
        FILE_ID = "file_id"

    class ReusedTextMatches:
        ID = "id"
        MATCH_TEXT = "match_text"
        MATCH_INDICES = "match_indices"
        PROPERTY = "property"
        FRAGMENT = "fragment"
        OBJECT_TYPE = "object_type"
        OBJECT_URL = "object_url"
        SIG_TO_FILE_ID = "sig_to_file_id"

    class Models:
        ID = "id"
        MODEL_ID = "model_id"
        FULL_NAME = "full_name"
        NAME = "name"
        AUTHOR = "author"
        SHA = "sha"
        DOWNLOADS = "downloads"
        LIKES = "likes"
        TRENDING_SCORE = "trending_score"
        CREATED_AT = "created_at"
        LAST_MODIFIED_DATE = "last_modified_date"
        PRIVATE = "private"
        GATED = "gated"
        PIPELINE_TAG = "pipeline_tag"
        LIBRARY_NAME = "library_name"
        COLLECTION_STATUS = "collection_status"

    class FileToModel:
        FILE_ID = "file_id"
        MODEL_ID = "model_id"
        SIGNATURE_ID = "signature_id"
        CALL_LINE_NO = "call_line_number"
        PARAM_LINE_NO = "param_line_number"
        IMPORT_ORIGIN = "import_origin"
        CALL_SIGNATURE = "call_signature"

    class FileSignatureMatches:
        ID = "id"
        FILE_ID = "file_id"
        SIGNATURE_ID = "signature_id"
        IMPORT_ORIGIN = "import_origin"
        CALL_SIGNATURE = "call_signature"
        CALL_LINE_NO = "call_line_number"
        MATCH_JSON = "match_json"
        CREATED_AT = "created_at"

    class FileASTEvidence:
        FILE_ID = "file_id"
        AST_DUMP = "ast_dump"
        CREATED_AT = "created_at"

    class Commits:
        ID = "id"
        COMMIT_ID = "commit_id"
        NODE_ID = "node_id"
        COMMITTED_AT = "committed_at"
        MESSAGE = "message"
        GIT_URL = "git_url"
        TREE_SHA = "tree_sha"
        TREE_URL = "tree_url"
        COMMENT_COUNT = "comment_count"
        HTML_URL = "html_url"
        VERIFIED = "verified"
        VERIFIED_REASON = "verified_reason"
        VERIFIED_AT = "verified_at"
        AUTHOR_NAME = "author_name"
        AUTHOR_ID = "author_id"
        AUTHOR_TYPE = "author_type"
        COMMITTER_NAME = "committer_name"
        COMMITTER_ID = "committer_id"
        COMMITTER_TYPE = "committer_type"
        PARENT_COUNT = "parent_count"
        PARENTS = "parents"
        TOTAL = "total"
        ADDITIONS = "additions"
        DELETIONS = "deletions"
        CHANGED_FILE_COUNT = "changed_file_count"
        REPO_ID = "repo_id"
        CHANGED_FILE_EXTRACTION_STATUS = "changed_file_extraction_status"

    class CommitComments:
        ID = "id"
        COMMENT_ID = "comment_id"
        NODE_ID = "node_id"
        URL = "url"
        COMMIT_SHA = "commit_sha"
        CREATED_AT = "created_at"
        CREATED_BY_NAME = "created_by_name"
        CREATED_BY_ID = "created_by_id"
        UPDATED_AT = "updated_at"
        AUTHOR_ASSOCIATION = "author_association"
        POSITION = "position"
        LINE = "line"
        FILE_PATH = "file_path"
        BODY = "body"
        COMMIT_ID = "commit_id"

    class CommitPreviousFilenames:
        COMMIT_FILE_ID = "commit_file_id"
        PREVIOUS_FILENAME = "previous_filename"

    class Issues:
        ID = "id"
        ISSUE_ID = "issue_id"
        URL = "url"
        NODE_ID = "node_id"
        NUMBER = "number"
        TITLE = "title"
        BODY = "body"
        USER_NAME = "user_name"
        USER_ID = "user_id"
        USER_TYPE = "user_type"
        LABEL_COUNT = "label_count"
        LABELS = "labels"
        STATE = "state"
        LOCKED = "locked"
        ASSIGNEE_COUNT = "assignee_count"
        ASSIGNEES = "assignees"
        MILESTONE = "milestone"
        COMMENT_COUNT = "comment_count"
        CREATED_AT = "created_at"
        UPDATED_AT = "updated_at"
        CLOSED_AT = "closed_at"
        CLOSED_BY_ID = "closed_by_id"
        CLOSED_BY_NAME = "closed_by_name"
        CLOSED_BY_TYPE = "closed_by_type"
        AUTHOR_ASSOCIATION = "author_association"
        TYPE_ID = "type_id"
        TYPE_NODE_ID = "type_node_id"
        TYPE_NAME = "type_name"
        TYPE_DESCRIPTION = "type_description"
        TYPE_COLOR = "type_color"
        TYPE_CREATED_AT = "type_created_at"
        TYPE_UPDATED_AT = "type_updated_at"
        ACTIVE_LOCK_REASON = "active_lock_reason"
        IS_PULL_REQUEST = "is_pull_request"
        SUB_ISSUE_SUMMARY_TOTAL = "sub_issue_summary_total"
        SUB_ISSUE_SUMMARY_COMPLETED = "sub_issue_summary_completed"
        SUB_ISSUE_SUMMARY_PERCENT_COMPLETED = "sub_issue_summary_percent_completed"
        REACTION_TOTAL_COUNT = "reaction_total_count"
        REACTION_PLUS1 = "reaction_plus1"
        REACTION_MINUS1 = "reaction_minus1"
        REACTION_LAUGH = "reaction_laugh"
        REACTION_HOORAY = "reaction_hooray"
        REACTION_CONFUSED = "reaction_confused"
        REACTION_HEART = "reaction_heart"
        REACTION_ROCKET = "reaction_rocket"
        REACTION_EYES = "reaction_eyes"
        STATE_REASON = "state_reason"
        COMMENT_COLLECTION_STATUS = "comment_collection_status"
        REPO_ID = "repo_id"

    class IssueComments:
        ID = "id"
        COMMENT_ID = "comment_id"
        URL = "url"
        CREATED_BY_NAME = "created_by_name"
        CREATED_BY_ID = "created_by_id"
        CREATED_AT = "created_at"
        UPDATED_AT = "updated_at"
        AUTHOR_ASSOCIATION = "author_association"
        BODY = "body"
        REACTION_TOTAL_COUNT = "reaction_total_count"
        REACTION_PLUS1 = "reaction_plus1"
        REACTION_MINUS1 = "reaction_minus1"
        REACTION_LAUGH = "reaction_laugh"
        REACTION_HOORAY = "reaction_hooray"
        REACTION_CONFUSED = "reaction_confused"
        REACTION_HEART = "reaction_heart"
        REACTION_ROCKET = "reaction_rocket"
        REACTION_EYES = "reaction_eyes"
        ISSUE_ID = "issue_id"

    class PullRequests:
        ID = "id"
        PULL_ID = "pull_id"
        URL = "url"
        CREATED_AT = "created_at"
        CLOSED_AT = "closed_at"
        MERGED_AT = "merged_at"
        MERGED_COMMIT_SHA = "merged_commit_sha"
        REQUESTED_REVIEWERS = "requested_reviewers"
        REQUESTED_TEAMS = "requested_teams"
        HEAD = "head"
        BASE = "base"
        MERGED = "merged"
        MERGED_BY_ID = "merged_by_id"
        MERGED_BY_NAME = "merged_by_name"
        MERGED_BY_TYPE = "merged_by_type"
        MERGEABLE = "mergeable"
        REBASEABLE = "rebaseable"
        REVIEW_COMMENTS = "review_comments"
        COMMITS = "commits"
        ADDITIONS = "additions"
        DELETIONS = "deletions"
        CHANGED_FILES = "changed_files"
        ISSUE_ID = "issue_id"
        REPO_ID = "repo_id"

    class PullRequestsToCommits:
        PULL_ID = "pull_id"
        COMMIT_ID = "commit_id"
        IS_MERGED = "is_merged"

    class Discussions:
        ID = "id"
        DISCUSSION_ID = "discussion_id"
        NODE_ID = "node_id"
        URL = "url"
        NUMBER = "number"
        TITLE = "title"
        BODY = "body"
        CATEGORY = "category"
        IS_ANSWERABLE = "is_answerable"
        IS_ANSWERED = "is_answered"
        ANSWER_URL = "answer_url"
        ANSWER_CHOSEN_AT = "answer_chosen_at"
        ANSWER_CHOSEN_BY_NAME = "answer_chosen_by_name"
        ANSWER_CHOSEN_BY_ID = "answer_chosen_by_id"
        CREATED_AT = "created_at"
        UPDATED_AT = "updated_at"
        CREATED_BY_NAME = "created_by_name"
        CREATED_BY_ID = "created_by_id"
        CREATED_BY_TYPE = "created_by_type"
        LABEL_COUNT = "label_count"
        LABELS = "labels"
        STATE = "state"
        STATE_REASON = "state_reason"
        LOCKED = "locked"
        COMMENT_COUNT = "comment_count"
        COMMENTS = "comments"
        COMMENT_IDS = "comment_ids"
        COMMENT_AUTHORS = "comment_authors"
        COMMENT_CREATED_AT = "comment_created_at"
        REACTION_TOTAL_COUNT = "reaction_total_count"
        REACTION_PLUS1 = "reaction_plus1"
        REACTION_MINUS1 = "reaction_minus1"
        REACTION_LAUGH = "reaction_laugh"
        REACTION_HOORAY = "reaction_hooray"
        REACTION_CONFUSED = "reaction_confused"
        REACTION_HEART = "reaction_heart"
        REACTION_ROCKET = "reaction_rocket"
        REACTION_EYES = "reaction_eyes"
        REPO_ID = "repo_id"
        
    class Releases:
        ID = "id"
        RELEASE_ID = "release_id"
        TAG_NAME = "tag_name"
        TARGET_COMMITISH = "target_commitish"
        NAME = "name"
        URL = "url"
        HTML_URL = "html_url"
        DRAFT = "draft"
        IMMUTABLE = "immutable"
        PRERELEASE = "prerelease"
        BODY = "body"
        CREATED_AT = "created_at"
        UPDATED_AT = "updated_at"
        PUBLISHED_AT = "published_at"
        NODE_ID = "node_id"
        AUTHOR_ID = "author_id"
        AUTHOR_NAME = "author_name"
        MENTIONS_COUNT = "mentions_count"
        TARBALL_URL = "tarball_url"
        ZIPBALL_URL = "zipball_url"
        ASSETS = "assets"
        REPO_ID = "repo_id"
        RELEASE_FILTER_STATUS = "release_filter_status"

    class ReusedFilesToReleases:
        ID = "id"
        REPO_ID = "repo_id"
        FILE_ID = "file_id"
        FILE_SHA = "file_sha"
        PATH = "path"
        SIZE = "size"
        RELEASE_ID = "release_id"
        DOWNLOAD_URL = "download_url"
        CREATED_AT = "created_at"

    class FileModelSnapshotsListsReleases:
        ID = "id"
        REPO_ID = "repo_id"
        FILE_ID = "file_id"
        RELEASE_ID = "release_id"
        COMMIT_ID = "commit_id"
        COMMIT_FILE_ID = "commit_file_id"
        MODEL_COUNT = "model_count"
        MODEL_ID = "model_id"
        MODEL_NAME = "model_name"
        CALL_LINE_NUMBER = "call_line_number"
        END_CALL_LINE_NUMBER = "end_call_line_number"
        PARAM_LINE_NUMBER = "param_line_number"
        END_PARAM_LINE_NUMBER = "end_param_line_number"
        IMPORT_ORIGIN = "import_origin"
        CALL_SIGNATURE = "call_signature"
        SIGNATURE_ID = "signature_id"
        PARSE_STATUS = "parse_status"
        PARSE_ERROR = "parse_error"

    class Tags:
        ID = "id"
        NAME = "name"
        NODE_ID = "node_id"
        COMMIT_SHA = "commit_sha"
        COMMIT_ID = "commit_id"
        RELEASE_ID = "release_id"
        REPO_ID = "repo_id"

    class Branches:
        ID = "id"
        NAME = "name"
        COMMIT_ID = "commit_id"
        COMMIT_SHA = "commit_sha"
        COMMIT_URL = "commit_url"
        PROTECTED = "protected"
        REPO_ID = "repo_id"

    class ReleaseBranchReachability:
        """
            CREATE TABLE IF NOT EXISTS release_branch_reachability (
            id INT NOT NULL AUTO_INCREMENT,
            repo_id INT UNSIGNED NOT NULL,
            release_id INT UNSIGNED NOT NULL,
            branch_id INT UNSIGNED NOT NULL,

            -- diagnostics
            tag_name VARCHAR(255) NOT NULL,
            tag_commit_sha CHAR(40) BINARY NOT NULL,
            branch_ref VARCHAR(255) NOT NULL,     -- e.g., 'origin/main' or 'main'

            reachable TINYINT(1) NOT NULL,        -- 1 if tag <= branch (ancestor), else 0
            compare_status ENUM('ahead','identical','behind','diverged','unknown')
                            NOT NULL DEFAULT 'unknown',
            commits_ahead INT NULL,               -- git rev-list --count <tag>..<branch>
            fp_commits_ahead INT NULL,            -- --first-parent variant (optional/fast)
            checked_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

            PRIMARY KEY (id),
            UNIQUE KEY uq_rbr (repo_id, release_id, branch_id),
            KEY idx_release (release_id),
            KEY idx_branch (branch_id),
            KEY idx_reachable (reachable)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
        """
        ID = "id"
        REPO_ID = "repo_id"
        RELEASE_ID = "release_id"
        BRANCH_ID = "branch_id"
        TAG_NAME = "tag_name"
        TAG_COMMIT_SHA = "tag_commit_sha"
        BRANCH_REF = "branch_ref"
        REACHABLE = "reachable"
        COMPARE_STATUS = "compare_status"
        COMMITS_AHEAD = "commits_ahead"
        FP_COMMITS_AHEAD = "fp_commits_ahead"
        CHECKED_AT = "checked_at"

    class ReleaseLineAssignments:
        """
        create table model_update.release_line_assignment
            (
                id              int auto_increment
                    primary key,
                repo_id         int          not null,
                release_id      int          not null,
                branch_id       int          not null,
                branch_ref      varchar(255) not null,
                tag_name        varchar(255) not null,
                tag_commit_sha  char(40)     not null,
                assigned_branch varchar(255) not null,
                assigned_reason varchar(64)  not null,
                fp_index        int          null,
                fp_found        tinyint(1)   not null,
                ambiguous       tinyint(1)   not null,
                computed_at     datetime     not null,
                constraint uniq_repo_rel_branch_tag
                    unique (repo_id, release_id, branch_id, tag_name)
            )
                charset = utf8mb4;
        """
        ID = "id"
        REPO_ID = "repo_id"
        RELEASE_ID = "release_id"
        BRANCH_ID = "branch_id"
        BRANCH_REF = "branch_ref"
        TAG_NAME = "tag_name"
        TAG_COMMIT_SHA = "tag_commit_sha"
        ASSIGNED_BRANCH = "assigned_branch"
        ASSIGNED_REASON = "assigned_reason"
        FP_INDEX = "fp_index"
        FP_FOUND = "fp_found"
        AMBIGUOUS = "ambiguous"
        COMPUTED_AT = "computed_at"

    class ReleaseLines:
        ID = "id"
        REPO_ID = "repo_id"
        RELEASE_LINE_ID = "release_line_id"
        BRANCH_ID = "branch_id"
        BRANCH_NAME = "branch_name"
        RELEASE_ID = "release_id"
        RELEASE_NAME = "release_name"
        FP_INDEX = "fp_index"
        PUBLISHED_DATE = "published_date"

    class ReleaseLineModelChanges:
        ID = "id"
        REPO_ID = "repo_id"
        RELEASE_LINE_ID = "release_line_id"
        PREV_RELEASE_ID = "prev_release_id"
        CURR_RELEASE_ID = "curr_release_id"
        PREV_MODEL_COUNT = "prev_model_count"
        CURR_MODEL_COUNT = "curr_model_count"
        MIGRATED_COUNT = "migrated_count"
        ADDED_COUNT = "added_count"
        REMOVED_COUNT = "removed_count"
        ADDED_MODEL_IDS = "added_model_ids"
        ADDED_MODEL_NAMES = "added_model_names"
        REMOVED_MODEL_IDS = "removed_model_ids"
        REMOVED_MODEL_NAMES = "removed_model_names"
        MIGRATED_FROM_MODEL_IDS = "migrated_from_model_ids"
        MIGRATED_FROM_MODEL_NAMES = "migrated_from_model_names"
        MIGRATED_TO_MODEL_IDS = "migrated_to_model_ids"
        MIGRATED_TO_MODEL_NAMES = "migrated_to_model_names"
        CREATED_AT = "created_at"
        IS_FIRST_ADOPTION = "is_first_adoption"